// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV4pIjkpohBh7seEfAKMMLwH_e9A0Gi3M',
    appId: '1:841770358596:web:8b26ea1ac014bd096de911',
    messagingSenderId: '841770358596',
    projectId: 'fir-auth-internship',
    authDomain: 'fir-auth-internship.firebaseapp.com',
    storageBucket: 'fir-auth-internship.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnurYAprgi4iogC_7S6F2tCnNeykg-LZM',
    appId: '1:841770358596:android:82823dabafbee93b6de911',
    messagingSenderId: '841770358596',
    projectId: 'fir-auth-internship',
    storageBucket: 'fir-auth-internship.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzWa9mj1sQQIBKX055FSEqHjSYfQjxnLU',
    appId: '1:841770358596:ios:1becafadc1ca82af6de911',
    messagingSenderId: '841770358596',
    projectId: 'fir-auth-internship',
    storageBucket: 'fir-auth-internship.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzWa9mj1sQQIBKX055FSEqHjSYfQjxnLU',
    appId: '1:841770358596:ios:1becafadc1ca82af6de911',
    messagingSenderId: '841770358596',
    projectId: 'fir-auth-internship',
    storageBucket: 'fir-auth-internship.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCV4pIjkpohBh7seEfAKMMLwH_e9A0Gi3M',
    appId: '1:841770358596:web:31e060f2b31516866de911',
    messagingSenderId: '841770358596',
    projectId: 'fir-auth-internship',
    authDomain: 'fir-auth-internship.firebaseapp.com',
    storageBucket: 'fir-auth-internship.firebasestorage.app',
  );
}
